export const EQUIPMENT_SAVE_RESTYPEID = 'EQUIPMENT_SAVE_RESTYPEID' //获取资源类型数据
export const EQUIPMENT_SAVE_DETAIL = 'EQUIPMENT_SAVE_DETAIL' //获取装备详情数据
export const GET_EQUIPMENT_UNIT = 'GET_EQUIPMENT_UNIT'
export const EDIT_STATUS = 'EDIT_STATUS' //编辑状态
export const EQUIPMENT_DUTY_ORG_ID = 'EQUIPMENT_DUTY_ORG_ID' //主管单位ID
export const GET_EQUIPMENT_RESOURCE_TYPE = 'GET_EQUIPMENT_RESOURCE_TYPE'