// export const RECEIVE_EXPERT_LIST_BY_PAGE = 'RECEIVE_EXPERT_LIST_BY_PAGE'; // 专家列表
// export const EXPERT_DETAIL = 'EXPERT_DETAIL';// 专家详情
// export const ADD_EXPERT = 'ADD_EXPERT';// 增加专家
// export const EDIT_EXPERT = 'EDIT_EXPERT';// 编辑专家
// export const EDIT_SAVE_EXPERT = 'EDIT_SAVE_EXPERT';// 编辑保存专家
// export const ADD_SAVE_EXPERT = 'ADD_SAVE_EXPERT';// 编辑保存专家
// export const DELETE_EXPERT = 'DELETE_EXPERT';// 删除专家
// export const DATE_FORMAT = 'DATE_FORMAT'; // 时间格式化
// export const SET_EXPERT_RESOURCE_TYPE_ID = 'SET_EXPERT_RESOURCE_TYPE_ID'; // 专家资源类型ID
// export const SET_EXPERT_POLITICS = 'SET_EXPERT_POLITICS'; // 政治面貌
// export const SET_EXPERT_SEX = 'SET_EXPERT_SEX'; // 性别
// export const SET_EXPERT_EDUCATION = 'SET_EXPERT_EDUCATION'; // 最高学历
// export const SET_EXPERT_AFFILIATION = 'SET_EXPERT_AFFILIATION';// 设置所属单位
// export const SET_EXPERT_DUTY = 'SET_EXPERT_DUTY';// 设置责任单位
export const EXPERT_SAVE_RESTYPEID = 'EXPERT_SAVE_RESTYPEID' //获取资源类型数据
export const EXPERT_SAVE_DETAIL = 'EXPERT_SAVE_DETAIL' //获取专家详情数据
export const GET_EXPERT_RESOURCE_TYPE = 'GET_EXPERT_RESOURCE_TYPE'
export const EDIT_STATUS = 'EDIT_STATUS' //编辑状态