export const HEIGHT_CONTENT = 'HEIGHT_CONTENT'
export const TABLE_HEIGHT = 'TABLE_HEIGHT'
export const TABLE_HEIGHT_INDEX = 'TABLE_HEIGHT_INDEX'
export const HEIGHT_CONTENT_INDEX = 'HEIGHT_CONTENT_INDEX'