export const MATERIAL_SAVE_RESTYPEID = 'MATERIAL_SAVE_RESTYPEID' //获取资源类型数据
export const MATERIAL_SAVE_DETAIL = 'MATERIAL_SAVE_DETAIL' //获取物资详情数据
export const GET_MATERIAL_UNIT = 'GET_MATERIAL_UNIT'
export const GET_MATERIAL_RESOURCE_TYPE = 'GET_MATERIAL_RESOURCE_TYPE'
// export const MATERIAL_ID = "MATERIAL_ID" //物资ID
// export const MATERIAL_DUTY_ORG_ID = "MATERIAL_DUTY_ORG_ID"  //物资主管单位
export const EDIT_STATUS = 'EDIT_STATUS' //编辑状态
export const MATERIAL_DUTY_ORG_ID = 'MATERIAL_DUTY_ORG_ID' //主管单位ID