export const GET_PROCESS_ARROW = 'GET_PROCESS_ARROW' //流程图组件
export const GET_PROCESS_ARROW_ID = 'GET_PROCESS_ARROW_ID'  //流程图ID
export const GET_TEMPLATE_DATA_LIST = 'GET_TEMPLATE_DATA_LIST'
export const SET_PROCESS_ARROW_MENU = 'SET_PROCESS_ARROW_MENU'
export const SET_PROCESS_ARROW_STATUS = 'SET_PROCESS_ARROW_STATUS'
export const CLEAR_PROCESS_ARROW_MENU = 'CLEAR_PROCESS_ARROW_MENU'//清楚缓存数据