export const REFUGE_SAVE_RESTYPEID = 'REFUGE_SAVE_RESTYPEID' //获取资源类型数据
export const REFUGE_SAVE_DETAIL = 'REFUGE_SAVE_DETAIL' //获取避险场所详情数据
export const EDIT_STATUS = 'EDIT_STATUS' //编辑状态
export const REFUGE_DUTY_ORG_ID = 'REFUGE_DUTY_ORG_ID' //主管单位ID
export const GET_REFUGE_RESOURCE_TYPE = 'GET_REFUGE_RESOURCE_TYPE'
