export const VEHICLE_SAVE_RESTYPEID = 'VEHICLE_SAVE_RESTYPEID' //获取资源类型数据
export const VEHICLE_SAVE_DETAIL = 'VEHICLE_SAVE_DETAIL' //获取设备详情数据
export const GET_VEHICLE_RESOURCE_TYPE = 'GET_VEHICLE_RESOURCE_TYPE'
export const EDIT_STATUS = 'EDIT_STATUS' //编辑状态
export const VEHICLE_DUTY_ORG_ID = 'VEHICLE_DUTY_ORG_ID' //主管单位ID
